name: Deployment
run-name: Deploying ${{ github.repository }}
on: push
jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        file: dockerfile
        tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
